name: Build and Test

on:
  push:
    branches:
      - Soumyo
      - Master
      - main
      
  pull_request:
    branches:
      -Soumyo

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup a JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: mvn clean package
      - name: Test
        run: |
          echo running test
          mvn test
        
